// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSRYu_I4z_i4JlN2K6zZRGtEV0YVM-RNc',
    appId: '1:662781096874:web:4ea8e1672b3fe892a4f1d3',
    messagingSenderId: '662781096874',
    projectId: 'streamit-a6570',
    authDomain: 'streamit-a6570.firebaseapp.com',
    storageBucket: 'streamit-a6570.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEeRJl1eXFZ-8i3jS9yESFSwIo3fpMnVI',
    appId: '1:662781096874:android:1eeb8d73a0820a81a4f1d3',
    messagingSenderId: '662781096874',
    projectId: 'streamit-a6570',
    storageBucket: 'streamit-a6570.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbGAT1XF7QXVwiLiuhoUaPzjD8L7jZq_U',
    appId: '1:662781096874:ios:03b26886c447d691a4f1d3',
    messagingSenderId: '662781096874',
    projectId: 'streamit-a6570',
    storageBucket: 'streamit-a6570.firebasestorage.app',
    iosBundleId: 'com.stream.streamIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbGAT1XF7QXVwiLiuhoUaPzjD8L7jZq_U',
    appId: '1:662781096874:ios:03b26886c447d691a4f1d3',
    messagingSenderId: '662781096874',
    projectId: 'streamit-a6570',
    storageBucket: 'streamit-a6570.firebasestorage.app',
    iosBundleId: 'com.stream.streamIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSRYu_I4z_i4JlN2K6zZRGtEV0YVM-RNc',
    appId: '1:662781096874:web:5b71064ed48e38d7a4f1d3',
    messagingSenderId: '662781096874',
    projectId: 'streamit-a6570',
    authDomain: 'streamit-a6570.firebaseapp.com',
    storageBucket: 'streamit-a6570.firebasestorage.app',
  );
}
